spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:49013/railway
spring.datasource.username=postgres
spring.datasource.password=QeZGSkfPjLIranJkxyHAWGbaxTLZcFej

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.error.include-stacktrace=always
server.error.include-message=always

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

reportes.carpeta=./reportes

server.forward-headers-strategy=framework

# ==========================================
# CONFIGURACIÓN DE CORREO (RECUPERACIÓN)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-correo@gmail.com
spring.mail.password=xxxxxxxxxxxxxxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Dominio base para el enlace de recuperación (local o producción en Railway)
app.base-url=http://localhost:8080